app_app:
    resource: "@AppAppBundle/Controller/AppController.php"
    type:     annotation
    prefix:   /

#API

api_todo_api:
    resource: "@APITodoApiBundle/Controller/TodoApiController.php"
    type:     rest
    prefix:   api